<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-ID9MJDP" name="com.wbl.testng.TestHomePage3" tests="1" failures="0" timestamp="11 Mar 2017 01:16:53 GMT" time="0.023" errors="1">
  <testcase name="test" time="0.023" classname="com.wbl.testng.TestHomePage3">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.wbl.testng.TestHomePage3.test() didn&#039;t finish within the time-out 10">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.wbl.testng.TestHomePage3.test() didn't finish within the time-out 10
	at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- test -->
</testsuite> <!-- com.wbl.testng.TestHomePage3 -->
